backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "store"
    label: "Store Management"
    files:
      - name: "products_list"
        label: "Cheese Products"
        file: "products.json"
        fields:
          - name: "products"
            label: "Products"
            widget: "list"
            summary: '{{fields.name}} - ৳{{fields.price}}'
            fields:
              - { label: "Product Name", name: "name", widget: "string" }
              - { label: "Price (TK)", name: "price", widget: "string" }
              - { label: "Description", name: "description", widget: "text", required: false }
              - { label: "Product Image", name: "image", widget: "image" }
